// <auto-generated />
using BooksMart.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BooksMart.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251125072614_AddForeignKeyForBookAndCategoryRelation")]
    partial class AddForeignKeyForBookAndCategoryRelation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BooksMart.Models.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price100")
                        .HasColumnType("float");

                    b.Property<double>("Price50")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorName = "Marvin Cole",
                            CategoryId = 1,
                            Description = "A gripping tale of mystery and redemption set in a forgotten town where secrets slowly unravel. Follow the journey of a man trying to reclaim his past while confronting the shadows that haunt him.",
                            ISBN = "BK10001001",
                            ListPrice = 110.0,
                            Price = 95.0,
                            Price100 = 85.0,
                            Price50 = 90.0,
                            Title = "Echoes of the Forgotten"
                        },
                        new
                        {
                            Id = 2,
                            AuthorName = "Diana Crest",
                            CategoryId = 2,
                            Description = "A heartwarming story about a young woman's return to her childhood valley, discovering love, loss, and the beauty hidden in everyday life. A gentle reminder that home is more than a place.",
                            ISBN = "BK20002001",
                            ListPrice = 45.0,
                            Price = 38.0,
                            Price100 = 28.0,
                            Price50 = 33.0,
                            Title = "Whispers of the Valley"
                        },
                        new
                        {
                            Id = 3,
                            AuthorName = "Felix Hart",
                            CategoryId = 3,
                            Description = "A suspense novel that follows an investigator racing against time to uncover a conspiracy threatening the peace of a bustling city. Every clue unravels a deeper layer of danger.",
                            ISBN = "BK30003001",
                            ListPrice = 60.0,
                            Price = 52.0,
                            Price100 = 40.0,
                            Price50 = 45.0,
                            Title = "Shadows Over Dawn"
                        },
                        new
                        {
                            Id = 4,
                            AuthorName = "Clara Monroe",
                            CategoryId = 3,
                            Description = "An enchanting romantic drama set under the glow of moonlit nights, where two unlikely people cross paths and discover the bittersweet nature of love and destiny.",
                            ISBN = "BK40004001",
                            ListPrice = 75.0,
                            Price = 70.0,
                            Price100 = 60.0,
                            Price50 = 65.0,
                            Title = "The Sugar Moon"
                        },
                        new
                        {
                            Id = 5,
                            AuthorName = "Ernest Hale",
                            CategoryId = 1,
                            Description = "A thrilling ocean adventure following a marine explorer who uncovers a hidden world beneath the waves. Courage, mystery, and danger collide deep in the unknown.",
                            ISBN = "BK50005001",
                            ListPrice = 35.0,
                            Price = 30.0,
                            Price100 = 22.0,
                            Price50 = 27.0,
                            Title = "Waves of Midnight"
                        },
                        new
                        {
                            Id = 6,
                            AuthorName = "Amelia Thorn",
                            CategoryId = 3,
                            Description = "A beautifully written fantasy novel about a young girl's discovery of a magical realm blooming beneath an ancient garden. Wonder, imagination, and bravery shape her unforgettable journey.",
                            ISBN = "BK60006001",
                            ListPrice = 28.0,
                            Price = 25.0,
                            Price100 = 21.0,
                            Price50 = 23.0,
                            Title = "Garden of Starlight"
                        });
                });

            modelBuilder.Entity("BooksMart.Models.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Horror"
                        });
                });

            modelBuilder.Entity("BooksMart.Models.Models.Book", b =>
                {
                    b.HasOne("BooksMart.Models.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
